name: ci-test

on:
  push:
    branches:
    - '*'

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install unit test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - run: tox
